
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int NEGATIVO = 11;
  public static final int DIVI = 5;
  public static final int DIGITO = 6;
  public static final int PIZQ = 9;
  public static final int POTENCIA = 7;
  public static final int SUMA = 2;
  public static final int MULTI = 4;
  public static final int PDER = 10;
  public static final int EOF = 0;
  public static final int RESULTADO = 8;
  public static final int error = 1;
  public static final int RESTA = 3;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SUMA",
  "RESTA",
  "MULTI",
  "DIVI",
  "DIGITO",
  "POTENCIA",
  "RESULTADO",
  "PIZQ",
  "PDER",
  "NEGATIVO"
  };
}

